:username: niveK77pur

:fullwidth: width=100%
:sidebysidewidth: width=49.7%

:profile-summary: http://github-profile-summary-cards.vercel.app/api/cards/
:readme-stats: https://github-readme-stats.vercel.app/api/pin/

:theme: transparent
:utc: 2

:user-github: https://github.com/{username}


:toc:

== Account Summary

image::{profile-summary}profile-details?username={username}&theme={theme}[{fullwidth}, link={user-github}]
image:{profile-summary}most-commit-language?username={username}&theme={theme}[{sidebysidewidth}, link={user-github}]
image:{profile-summary}repos-per-language?username={username}&theme={theme}[{sidebysidewidth}, link={user-github}]
image:{profile-summary}stats?username={username}&theme={theme}[{sidebysidewidth}, link={user-github}]
image:{profile-summary}productive-time?username={username}&theme={theme}&utcOffset={utc}[{sidebysidewidth}, link={user-github}]

== My Configurations

image:{readme-stats}?username={username}&repo=77configs&theme={theme}[{sidebysidewidth}, link={user-github}/77configs]
image:{readme-stats}?username={username}&repo=nvim&theme={theme}[{sidebysidewidth}, link={user-github}/nvim]

== Piano

=== MIDI Input inside of NeoVim

As someone who is very enthusiastic about the piano, but also loves working in the terminal using NeoVim, I have always found myself missing the ability to write my LilyPond scores using MIDI right from the comfort of NeoVim. https://frescobaldi.org/[Frescobaldi] always filled this gap, but thanks to NeoVim's async job capabilities, I was finally able to make it work *inside of* NeoVim! The `lilypond-midi-input` backend is written in Rust, and is spawned by the `midi-input.nvim` NeoVim plugin! The plugin further provides many niceties to make working with MIDI as nice as possible.

image:{readme-stats}?username={username}&repo=midi-input.nvim&theme={theme}[{sidebysidewidth}, link={user-github}/midi-input.nvim]
image:{readme-stats}?username={username}&repo=lilypond-midi-input&theme={theme}[{sidebysidewidth}, link={user-github}/lilypond-midi-input]

=== My LilyPond Music Sheets Archive

I created a separate organization where I store/archive all my LilyPond sheet music. You might be familiar with https://github.com/niveK77pur/VinLudens_Music-Sheets[the old archived repository], but it ended up becoming unmanagable. The organization holds one repository per sheet, allowing to use CI/CD to automatically compile the output PDF from the source code. It's very neat, I'm very happy with it; check it out!

https://github.com/VinLudens
